version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.web
    restart: always
  nscc360:
    build: 
      context: ./nscc360
      dockerfile: Dockerfile.web
    restart: always
    ports:
      - "8003:80"
    