version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
  nscc360:
    build: 
      context: ./nscc360
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:80"